apiVersion: v1
kind: Service
metadata:
  name: ganache
  labels:
    app: ganache
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ganache
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8545
