apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: election-dapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Osinachi-Uro/Deploying-and-Scale-Ethereum-Node-and-DApp-on-Kubernetes
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: election-dapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true