apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
data:
  service.slack: |
    token: $slack-token
    username: ArgoCD Bot
    icon: ":rocket:"
  trigger.on-deployed: |
    when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
    send: [app-deployed]
  trigger.on-sync-failed: |
    when: app.status.operationState.phase == 'Failed'
    send: [app-sync-failed]
  template.app-deployed: |
    message: |
      :tada: Application {{.app.metadata.name}} is now running version {{.app.status.sync.revision}} in namespace {{.app.metadata.namespace}}.
    slack:
      attachments: |
        [{
          "color": "#18be52",
          "blocks": [
            {
              "type": "section",
              "text": { "type": "mrkdwn", "text": ":tada: *Application {{.app.metadata.name}}* is now running version `{{.app.status.sync.revision}}` in namespace `{{.app.metadata.namespace}}`" }
            }
          ]
        }]
  template.app-sync-failed: |
    message: |
      :x: Application {{.app.metadata.name}} failed to sync.
    slack:
      attachments: |
        [{
          "color": "#e11d48",
          "blocks": [
            {
              "type": "section",
              "text": { "type": "mrkdwn", "text": ":x: *Application {{.app.metadata.name}}* failed to sync." }
            }
          ]
        }]
