name: Deploy Election DApp

on:
#   workflow_run:
#     workflows: ["Docker build-push Election DApp Image to ECR"]
#     types:
#       - completed 
  push:
    branches: [ main ]
    paths:
      - 'alerts/*'
      - '.github/workflows/argocd-slack-alert.yaml'
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Working directory"
        required: true
        default: "alerts"
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  deploy:
    name: Configure alerts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}


    - name: Configure ArgoCD - Slack Notification
      run: |
        echo "Configuring ArgoCD notification to Slack"
        kubectl apply -f alerts/argocd-notifications-cm.yaml
        kubectl apply -f alerts/argocd-notifications-secret.yaml
      env: 
        slack_token: ${{ env.SLACK_TOKEN }}
        
    # - name: Patch Slack token secret
    #   run: |
    #     echo "Ensuring Slack token secret exists..."
    #     if ! kubectl get secret argocd-notifications-secret -n argocd >/dev/null 2>&1; then
    #       echo "Secret does not exist. Creating..."
    #       kubectl create secret generic argocd-notifications-secret \
    #         -n argocd \
    #         --from-literal=slack-token="${{ secrets.SLACK_TOKEN }}"
    #     else
    #       echo "Secret exists. Patching..."
    #       kubectl patch secret argocd-notifications-secret -n argocd \
    #         --type merge \
    #         -p "{\"stringData\": {\"slack-token\": \"${{ secrets.SLACK_TOKEN }}\"}}"
    #     fi


    - name: Create ArgoCD Application
      run: |
        echo "Creating ArgoCD Application..."
        kubectl apply -f alerts/argocd-application.yaml