name: Docker build-push & Deploy Election DApp to EKS Cluster

on:
  push:
    branches: 
      - main
    paths:
      - .github/workflows/build-push-election-dapp.yaml
      - DApp/*
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Working directory"
        required: true
        default: "DApp"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check if Docker is installed
      run: |
          if ! command -v docker &> /dev/null
          then
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo apt-get install -y docker-compose
          fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag Docker image
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY_NAME }}:latest ./

    - name: Push image to Amazon ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY_NAME }}:latest

