name: Deploy EKS Infrastructure on AWS

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-infra.yaml
      - infra/*.tf
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Working directory"
        required: true
        default: "infra"

env:
  TF_VAR_eks_admin_user_arn: ${{ secrets.EKS_ADMIN_USER_ARN }}
  TF_VAR_eks_admin_username: ${{ secrets.EKS_ADMIN_USERNAME }}
  TF_VAR_region: ${{ secrets.AWS_REGION }}
  TF_VAR_cluster_name: ${{ secrets.EKS_CLUSTER_NAME }}


jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Clear Cache Temporarily
        run: rm -rf .terraform .terraform.lock.hcl ~/.terraform.d./

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Apply
        run: terraform apply -auto-approve
