# name: Deploy Ganache to EKS

# on:
#   workflow_run:
#     workflows: ["Deploy EKS Infrastructure on AWS"]
#     types:
#       - completed  
#   push:
#     branches:
#       - main
#     paths:
#       - .github/workflows/deploy-ganache.yaml
#       - ganache/*
#   workflow_dispatch:
#     inputs:
#       working_directory:
#         description: "Working directory"
#         required: true
#         default: "ganache"

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_REGION }}

#     - name: Setup kubectl
#       uses: azure/setup-kubectl@v3

#     - name: Setup Helm
#       uses: azure/setup-helm@v3
    
#     - name: Setup kubeconfig for EKS
#       run: |
#         aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

#     - name: Confirm EKS connection
#       run: kubectl get nodes

#     - name: Install Ganache to EKS via Helm
#       run: |
#         helm upgrade --install ganache ./ganache

#     - name: Wait for external IP (optional)
#       run: |
#         echo "Waiting for LoadBalancer IP..."
#         sleep 30
#         kubectl get svc ganache
