name: Destroy EKS Infrastructure on AWS

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Working directory"
        required: true
        default: "infra"

env:
  Access Key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  Secret Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_eks_admin_user_arn: ${{ secrets.EKS_ADMIN_USER_ARN }}
  TF_VAR_eks_admin_username: ${{ secrets.EKS_ADMIN_USERNAME }}
  TF_VAR_region: ${{ secrets.AWS_REGION }}
  TF_VAR_cluster_name: ${{ secrets.EKS_CLUSTER_NAME }}
  TF_VAR_slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}


jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
